### PR TITLE
Uffizzi PR: Add Celery to docker-compose.uffizzi.yml

### PR DESCRIPTION
**Pull request by ShrutiC-git**
Add celery and other needed dependencies in docker-compose.uffizzi.yml. 

With these dependencies added, jobs that were always stuck in the "queued" phase can move from the queue and be executed.

### CODE REVIEW

**Comment by ShrutiC-git** [comment]
seems deployment has failed on this one. Monitoring

**Comment by ShrutiC-git** [comment]
hey, @ieaves, updated the PR.

It seems the error I mentioned about the tenants could have been related to the container names not being parsed correctly. The underscore in celery containers was throwing a server error on our end - which makes me think that another container dependent on either celery or flower was unable to connect to it, and threw the error we were discussing. 

I'm not seeing the error anymore, and everything looks good to me. 

The jobs are passing, and I can check the graphs and tables for the connection.

**Comment by ShrutiC-git** [comment]
hey, @ieaves, commenting here to put this on your radar in case this PR was missed (or maybe I miscommunicated). This PR will add celery dependency into Uffizzi environments. 

The PR which was merged earlier does not contain celery, so `grai` environments might not work as needed. That should be fixed with this PR. 

You can also check the environment built for this PR before merging to make sure things work as expected. 

Let me know if there's anything that's missing in this :)

**Comment by ieaves** [comment]
Hey @ShrutiC-git This LGTM, merging :)

**Pull request merged**
