### PR TITLE
Dbt

### PR DESCRIPTION
**Pull request by ieaves**
Changes:
* Adds integration support for DBT sources, seeds, and models from the manifest.json

### CODE REVIEW

**Comment by ieaves** [comment]
@edlouth I think this is good to merge but I'm leaving it up in case you want to take a look / review. Happy to hop on a call and walk you through the implementation as well so you aren't going in blind if you were interested :).

**Comment by edlouth** [comment]
Looks good, my only comment would be that the two files in `.github/webhooks` are named oddly as copies.

**Comment by ieaves** [comment]
Trololol, the copy's were hidden behind the width of my editor display. Fixed now!

**Review by edlouth — APPROVED** [review]
Looks good to me

**Pull request merged**
