### PR TITLE
Added html to email verification template and deleted the older text template

### PR DESCRIPTION
**Pull request by kunaldhand**

### CODE REVIEW

**Comment by edlouth** [comment]
A quick question, you have created a new html file, will this automatically be used by Django? I note that some of the grai-server tests are failing, with an error message regarding a missing file.  We would need to get these tests to pass, before we can merge the change.

**Comment by kunaldhand** [comment]
> A quick question, you have created a new html file, will this automatically be used by Django? I note that some of the grai-server tests are failing, with an error message regarding a missing file (https://github.com/grai-io/grai-core/actions/runs/6496798029/job/17644546965?pr=714). We would need to get these tests to pass, before we can merge the change.

The earlier template used by grai was a simple text file, the proposed html file should work same as the text file before. If in case that didn't work then I believe we need to make changes in Django files. I actually don't know much about Django to be honest.
For the grai-servers tests that are failing is because of authentication is missing in the files. You can check in the details of errors.

**Comment by kunaldhand** [comment]
> > A quick question, you have created a new html file, will this automatically be used by Django? I note that some of the grai-server tests are failing, with an error message regarding a missing file (https://github.com/grai-io/grai-core/actions/runs/6496798029/job/17644546965?pr=714). We would need to get these tests to pass, before we can merge the change.
> 
> The earlier template used by grai was a simple text file, the proposed html file should work same as the text file before. If in case that didn't work then I believe we need to make changes in Django files. I actually don't know much about Django to be honest. For the grai-servers tests that are failing is because of authentication is missing in the files. You can check in the details of errors.

I just went through some errors and found that those errors are because file is changed from "email_verification.txt" to "email_verification_template.html"

**Comment by kunaldhand** [comment]
Screenshot_2023-10-12-20-39-26-79_40deb401b9ffe8e1df2f1cc5ba480b12
These errors are in tests-server file, other files are having authentication issue. Kindly check and let me know @edlouth

**Comment by edlouth** [comment]
No worries, I can help with the Django update required.

In this [file](https://github.com/grai-io/grai-core/blob/fc1473607ff26296756e1af4f1473aaee7cbb8bd/grai-server/app/auth/validation.py#L25C1-L25C1) we need to add a line like this

```
html_message = render_to_string("auth/email_verification_template.html", c)
```

and change

```
send_mail(
        subject,
        email_message,
        settings.EMAIL_FROM,
        [user.username],
        fail_silently=False,
    )
```
to
```
send_mail(
        subject,
        email_message,
        settings.EMAIL_FROM,
        [user.username],
        fail_silently=False,
        html_message=html_message,
    )
```

We will also not delete the existing `.txt` file, as this will be used for email clients that don't support html.

**Pull request closed without merging**
